---
apiVersion: "extensions/v1beta1"
kind: "Deployment"
metadata:
  labels:
    project: "open-api"
    app: "ms-main"
  name: "ms-main"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "ms-main"
  template:
    metadata:
      labels:
        project: "open-api"
        app: "ms-main"
    spec:
      containers:
      - name: "ms-main"
        image: "ms-main:v002"
        ports:
        - containerPort: 80
          name: "http"
          protocol: "TCP"
        env:
        - name: "KUBERNETES_NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: "metadata.namespace"
        imagePullPolicy: "IfNotPresent"

