---
apiVersion: "v1"
kind: "Service"
metadata:
  labels:
    project: "open-api"
    app: "ms-main"
  name: "ms-main"
spec:
  ports:
  - port: 80
    protocol: "TCP"
    targetPort: 80
  selector:
    app: "ms-main"
  type: "LoadBalancer"
