---
apiVersion: "v1"
kind: "Service"
metadata:
  labels:
    team-name: "open-api"             # open-api, digital-modernization, ca
    app-name: "ms-main"               # property
    app-type: "ms"                    # ms,
    ms-type: "experience"             # experience, foundation, core, support etc.
    environment: "development"        # development, test, stage, production
    version: "v002"
    role: "frontend"                  # backend, frontend, database etc.
  name: "ms-main"
spec:
  ports:
  - port: 80
    protocol: "TCP"
    targetPort: 80
  selector:
    app: "ms-main"
  type: "LoadBalancer"

