---
apiVersion: "extensions/v1beta1"
kind: "Deployment"
metadata:
  labels:
    team-name: "open-api"
    app-name: "ms-main"
  name: "ms-main"
spec:
  replicas: 1
  selector:
    matchLabels:
      app-name: "ms-main"
  template:
    metadata:
      labels:
        team-name: "open-api"
        app-name: "ms-main"
    spec:
      containers:
      - name: "ms-main"
        image: "ms-main:v002"
        ports:
        - containerPort: 80
          name: "http"
          protocol: "TCP"
